### ISSUE TITLE
The method 'read' isn't defined for the type 'BuildContext'. (Documentation)

### ISSUE THREAD

**Issue by 777genius** [crizant/flutter_route_aware_example#1]
I have this error here. 

https://github.com/crizant/flutter_route_aware_example/blob/3301c06046aafe56dbe6d20a9f2678fe24774bf2/lib/route_aware_state.dart#L19

![image](https://user-images.githubusercontent.com/13103045/131005693-d5fa29ce-ae86-4811-aba6-85ba4ef00975.png)

**Comment by crizant** [comment]
`context.read` is defined in the [`provider`](https://pub.dev/packages/provider) package, check the version you installed.
Also, please make sure you have the latest version of Flutter. Run `flutter clean` then build again when necessary.
